version: '3.9'

services:
  ui:
    image: andreclerigo/payload-dashboard-ui:arm64-latest
    container_name: ui
    ports:
      - "80:3030"
    volumes:
      - .:/ui
      - /ui/node_modules
    command: "yarn dev --host"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
